apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-echo
  labels:
    app: tcp-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-echo
  template:
    metadata:
      labels:
        app: tcp-echo
    spec:
      containers:
      - name: tcp-echo
        image: tkircsi/tcp-echo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-echo-service
spec:
  selector:
    app: tcp-echo
  ports:
  - port: 5000
    targetPort: 5000
